name: Build and Deploy

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.3
        with:
          node-version: '14' # specify your desired node version here

      - name: Install dependencies
        run: npm install

      - name: Electron Forge Action
        uses: yinxulai/actions-electron-forge@0.0.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          package_root: . # optional, default is .
          script_name: publish # optional, default is publish
          release: true # optional

